=== AlezZ743/LLMM/Actividades/tema5/EJ2/alumnos.dtd
<!ELEMENT lista_alumnos (alumno*)>
<!ELEMENT alumno (nombre, apellidos, domicilio, telefono+, equipo?, aficion*, (provincia | pais), comentarios?, (evaluacion, calificacion)+)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT domicilio (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ATTLIST telefono 
          origen (propio | padre | madre | tutor) #REQUIRED>

<!ELEMENT equipo (#PCDATA)>
<!ELEMENT aficion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT pais (#PCDATA)>

<!ELEMENT comentarios ANY>

<!ELEMENT evaluacion (#PCDATA)>
<!ELEMENT calificacion (#PCDATA)>

<!ATTLIST alumno 
          num_alumno ID #REQUIRED
          altura_cm CDATA #IMPLIED
          sexo (hombre | mujer) #IMPLIED
          ayudado_por IDREF #IMPLIED>

=== AlezZ743/LLMM/Actividades/tema5/EJ2/alumnos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lista_alumnos SYSTEM "alumnos.dtd">
<lista_alumnos>
    <alumno num_alumno="A01" sexo="hombre" altura_cm="180">
        <nombre>Sergio</nombre>
        <apellidos>García López</apellidos>
        <domicilio>Calle Mayor 5, Madrid</domicilio>
        <telefono origen="propio">600111222</telefono>
        <telefono origen="padre">600333444</telefono>
        <equipo>Baloncesto</equipo>
        <aficion>Lectura</aficion>
        <aficion>Ajedrez</aficion>
        <provincia>Madrid</provincia>
        <comentarios>Alumno muy participativo en <equipo>Baloncesto</equipo>.</comentarios>
        <evaluacion>Primera</evaluacion>
        <calificacion>8</calificacion>
        <evaluacion>Segunda</evaluacion>
        <calificacion>9</calificacion>
    </alumno>

    <alumno num_alumno="A02" sexo="mujer" ayudado_por="A01">
        <nombre>Elena</nombre>
        <apellidos>Martínez Ruiz</apellidos>
        <domicilio>Av. Libertad 10, Lyon</domicilio>
        <telefono origen="tutor">655777888</telefono>
        <pais>Francia</pais>
        <evaluacion>Primera</evaluacion>
        <calificacion>7</calificacion>
    </alumno>
</lista_alumnos>
