=== AlezZ743/LLMM/Actividades/tema5/EJ3/pedidos.dtd
<!ELEMENT pedidos (pedido+)>
<!ELEMENT pedido ((empresa | cliente), producto+, fecha, factura?)>

<!ELEMENT empresa (#PCDATA)>
<!ATTLIST empresa 
          CIF ID #REQUIRED
          sector NMTOKEN #IMPLIED
          actividad NMTOKENS #IMPLIED>

<!ELEMENT cliente (#PCDATA)>
<!ATTLIST cliente 
          NIF ID #REQUIRED>

<!ELEMENT producto (#PCDATA)>
<!ATTLIST producto 
          id_prod ID #REQUIRED>

<!ELEMENT fecha (#PCDATA)>

<!ELEMENT factura (emisor, total, fecha)>
<!ATTLIST factura 
          numfactura ID #REQUIRED
          cliente IDREF #REQUIRED
          productos IDREFS #REQUIRED>

<!ELEMENT emisor (#PCDATA)>
<!ELEMENT total (#PCDATA)>

<!ENTITY MiEmpresa "Esta es mi Empresa">

=== AlezZ743/LLMM/Actividades/tema5/EJ3/pedidos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos SYSTEM "pedidos.dtd">
<pedidos>
    <pedido>
        <empresa CIF="B12345678" sector="Tecnologia" actividad="Software_IT Consultoria_Sistemas">Tech Solutions S.L.</empresa>
        <producto id_prod="P01">Servidor Dell R740</producto>
        <producto id_prod="P02">Switch Cisco 24p</producto>
        <fecha>2026-04-29</fecha>
        <factura numfactura="F001" cliente="B12345678" productos="P01 P02">
            <emisor>&MiEmpresa;</emisor>
            <total>5400.50</total>
            <fecha>2026-04-30</fecha>
        </factura>
    </pedido>

    <pedido>
        <cliente NIF="A44556677Z">Juan Pérez García</cliente>
        <producto id_prod="P03">Portátil HP ProBook</producto>
        <fecha>2026-04-28</fecha>
        </pedido>
</pedidos>
